name: Install detekt

on:
  push:
    branches:
      - main
      - detekt
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.23.8

      - name: Run detekt
        run: detekt-cli --version